table Fact_Sales
	lineageTag: 6cabac50-8372-4dff-abe6-a39a8be4610b

	column 'Order ID'
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: d8bf8680-1fb4-450d-bd01-fc954935637f
		summarizeBy: none
		sourceColumn: Order ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Order Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 2406fca6-c84b-49ed-aefa-6749fedceca7
		summarizeBy: none
		sourceColumn: Order Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Customer ID'
		dataType: string
		isHidden
		lineageTag: 435c923e-e99b-4af4-ba42-3b0a349df6ed
		summarizeBy: none
		sourceColumn: Customer ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5e1de7dd-d004-4de1-b17f-697b30d16710
		summarizeBy: none
		sourceColumn: Quantity

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Unit Price'
		dataType: double
		isHidden
		lineageTag: d42af784-329b-4371-aae5-3feea7758c67
		summarizeBy: none
		sourceColumn: Unit Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discount
		dataType: double
		isHidden
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f0274fc5-5364-4be3-8440-970dbb0ad1c7
		summarizeBy: none
		sourceColumn: Discount

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Delivery Days'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c7a3506a-b666-469a-97ad-4da19bc20186
		summarizeBy: none
		sourceColumn: Delivery Days

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Customer Rating'
		dataType: double
		isHidden
		formatString: 0.0
		lineageTag: 8c0770f9-9676-4209-8eb2-e1c7a088c0d5
		summarizeBy: none
		sourceColumn: Customer Rating

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Revenue
		dataType: double
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 624637cb-1a1e-4896-8dd1-1061d42fed9a
		summarizeBy: none
		sourceColumn: Revenue

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Gross Profit' = 'Fact_Sales'[Revenue] - ('Fact_Sales'[Quantity] * 'Fact_Sales'[Unit Price] * 0.6)
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 21ef6f1f-b6aa-40df-842e-aa901c0cfc08
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Discount Group' =
			
			SWITCH(
			    TRUE(),
			    Fact_Sales[Discount] < 0.10, "0-10%",
			    Fact_Sales[Discount] <= 0.20, "10-20%",
			    "20%+"
			)
		isHidden
		lineageTag: e4b8a41e-29c5-40c5-a119-5fa11339303e
		summarizeBy: none
		sortByColumn: 'Discount Group Sort'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Discount Group Sort' =
			
			SWITCH(
			    TRUE(),
			    Fact_Sales[Discount] < 0.10, 1,
			    Fact_Sales[Discount] <= 0.20, 2,
			    3
			)
		isHidden
		formatString: 0
		lineageTag: ae3f03da-c159-42d9-9a18-200e6e94e636
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Product Category'
		dataType: string
		isHidden
		lineageTag: d87efee0-febf-4cc4-b02b-5cae48006d4b
		summarizeBy: none
		sourceColumn: Product Category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		isHidden
		lineageTag: 155441cb-5d45-48e6-8644-2b68aa93603b
		summarizeBy: none
		sourceColumn: Region

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Payment Method'
		dataType: string
		isHidden
		lineageTag: be23b130-029c-492c-bfad-173413ac752e
		summarizeBy: none
		sourceColumn: Payment Method

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a84b162a-54d6-4d4e-97f1-2541b34f265f
		summarizeBy: none
		sourceColumn: Quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Quarter Name'
		dataType: string
		isHidden
		lineageTag: 717ac669-8390-4f1f-ac0c-376035e428fc
		summarizeBy: none
		sourceColumn: Quarter Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Fact_Sales = m
		mode: import
		source =
				let
				  Źródło = Csv.Document(File.Contents(DatasetFilePath),[Delimiter=",", Columns=12, QuoteStyle=QuoteStyle.None]),
				  #"Nagłówki o podwyższonym poziomie" = Table.PromoteHeaders(Źródło, [PromoteAllScalars = true]),
				    #"Zmieniono typ z ustawieniami regionalnymi" = Table.TransformColumnTypes(#"Nagłówki o podwyższonym poziomie", {{"unit_price", type number}, {"discount", type number}, {"revenue", type number}}, "en-US"),
				    #"Zmieniono typ z ustawieniami regionalnymi1" = Table.TransformColumnTypes(#"Zmieniono typ z ustawieniami regionalnymi", {{"order_date", type date}}, "en-US"),
				    #"Zmieniono typ z ustawieniami regionalnymi2" = Table.TransformColumnTypes(#"Zmieniono typ z ustawieniami regionalnymi1", {{"customer_rating", type number}}, "en-US"),
				    #"Sorted Rows" = Table.Sort(#"Zmieniono typ z ustawieniami regionalnymi2",{{"order_id", Order.Descending}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Sorted Rows",{{"order_id", Int64.Type}}),
				    #"Inserted Quarter" = Table.AddColumn(#"Changed Type", "Quarter", each Date.QuarterOfYear([order_date]), Int64.Type),
				    #"Added Custom" = Table.AddColumn(#"Inserted Quarter", "Quarter_Name", each "Q" & Text.From([Quarter])),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"delivery_days", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"order_id", "Order ID"}, {"order_date", "Order Date"}, {"customer_id", "Customer ID"}, {"product_category", "Product Category"}, {"region", "Region"}, {"quantity", "Quantity"}, {"unit_price", "Unit Price"}, {"discount", "Discount"}, {"payment_method", "Payment Method"}, {"delivery_days", "Delivery Days"}, {"customer_rating", "Customer Rating"}, {"revenue", "Revenue"}, {"Quarter_Name", "Quarter Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Nawigacja

