table Dim_Customer
	lineageTag: 20add968-575b-4c38-a03e-d0390db3b2f6

	column 'Customer ID'
		dataType: int64
		formatString: 0
		lineageTag: 4d3434af-be1a-4302-acbd-12cfe1a43d14
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: fc30e6bd-95c6-404a-b19c-1bb2a05a3373
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Dim_Customer = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\semen\Desktop\PRACA\archive\ecommerce_sales_analytics_5000.csv"), [Delimiter = ",", Columns = 12, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"order_id", Int64.Type}, {"order_date", type date}, {"customer_id", Int64.Type}, {"product_category", type text}, {"region", type text}, {"quantity", Int64.Type}, {"unit_price", type number}, {"discount", type number}, {"payment_method", type text}, {"delivery_days", Int64.Type}, {"customer_rating", type number}, {"revenue", type number}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed column type",{"customer_id", "region"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"customer_id"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Duplicates",{{"customer_id", "Customer ID"}, {"region", "Region"}})
				in
				  #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

