table Dim_Category
	lineageTag: 3298a652-ce5f-4bfb-a5c3-cd19e79e2ca9

	column 'Product Category'
		dataType: string
		lineageTag: 60eac302-45b4-447e-996e-f97bb57b1b42
		summarizeBy: none
		sourceColumn: Product Category

		annotation SummarizationSetBy = Automatic

	column 'Category ID'
		dataType: int64
		formatString: 0
		lineageTag: 94bf07da-9339-466b-84e2-7eb2043cc50b
		summarizeBy: none
		sourceColumn: Category ID

		annotation SummarizationSetBy = Automatic

	partition Dim_Category = m
		mode: import
		source =
				let
				  Źródło = Csv.Document(File.Contents("C:\Users\semen\Desktop\PRACA\archive\ecommerce_sales_analytics_5000.csv"), [Delimiter = ",", Columns = 12, QuoteStyle = QuoteStyle.None]),
				  #"Nagłówki o podwyższonym poziomie" = Table.PromoteHeaders(Źródło, [PromoteAllScalars = true]),
				    #"Zmieniono typ z ustawieniami regionalnymi" = Table.TransformColumnTypes(#"Nagłówki o podwyższonym poziomie", {{"unit_price", type number}, {"discount", type number}, {"revenue", type number}}, "en-US"),
				    #"Zmieniono typ z ustawieniami regionalnymi1" = Table.TransformColumnTypes(#"Zmieniono typ z ustawieniami regionalnymi", {{"order_date", type date}}, "en-US"),
				    #"Zmieniono typ z ustawieniami regionalnymi2" = Table.TransformColumnTypes(#"Zmieniono typ z ustawieniami regionalnymi1", {{"customer_rating", type number}}, "en-US"),
				    #"Sorted Rows" = Table.Sort(#"Zmieniono typ z ustawieniami regionalnymi2",{{"order_id", Order.Descending}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Sorted Rows",{{"order_id", Int64.Type}}),
				    #"Inserted Quarter" = Table.AddColumn(#"Changed Type", "Quarter", each Date.QuarterOfYear([order_date]), Int64.Type),
				    #"Added Custom" = Table.AddColumn(#"Inserted Quarter", "Quarter_Name", each "Q" & Text.From([Quarter])),
				    #"Removed Other Columns" = Table.SelectColumns(#"Added Custom",{"product_category"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Category ID"}, {"product_category", "Product Category"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Nawigacja

	annotation PBI_ResultType = Table

